version: '2'
services:
  haproxy:
    image: m21lab/haproxy:1.6.2
    links:
      - letsencrypt
    volumes_from:
      - letsencrypt

  letsencrypt:
    image: m21lab/letsencrypt:1.0
    environment:
      DOMAINS: 'tribus.studio'
      EMAIL: 'william@tribus.studio'
      OPTIONS: '--staging'

  registry:
    volumes_from:
      - letsencrypt:ro
    environment:
      REGISTRY_HTTP_SECRET: "NUbGWYdD5wHQRLTJLyvzxCvVeJopzcTD"
      REGISTRY_HTTP_TLS_CERTIFICATE: /etc/letsencrypt/live/tribus.studio/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /etc/letsencrypt/live/tribus.studio/privkey.pem

  registry-ui:
    environment:
      FORCE_SSL: 'true'
      ENV_REGISTRY_PROXY_FQDN: 'tribus.studio'
      ENV_DOCKER_REGISTRY_USE_SSL: 1